### PR TITLE
Early rescan when all network connections closed

### PR DESCRIPTION
**Pull request by willscott**
Partially address #34

### CODE REVIEW

**Comment by Stebalien** [comment]
What's the motivation for this change?

**Comment by willscott** [comment]
The real event of 'network change' that should reset autonat is likely to be an approximation - mostly because the underlying host won't always or reliably know that the network environment has changed.

Some options:
* We could poll `net.InterfaceAddrs()` to see if local addresses have changed from DHCP.
* We could try [platform specific](https://stackoverflow.com/questions/55369964/detect-network-connection-availability-changes) methods like netlink sockets to try to get notified of network changes as the OS understands them.

The heuristic here is that if your network gets disconnected or switched, your existing connections will all time out / close. If you find yourself with no active connections (and you expect to generally be maintaining at least some connections in a passive state) that's an indication that you probably should have less confidence in your previous externally visible address remaining the same.

**Comment by Stebalien** [comment]
Got it. My concern here is that, when we disconnect from all peers, we likely have no internet so this will likely fail. Then, when we start connecting to new peers, we won't take any additional actions.

The correct way to do this would be to listen for the `EvtLocalAddressesUpdated` event (defined in go-libp2p-core) from the libp2p event bus (`host.EventBus()`).

Unfortunately..., it doesn't look like we've hooked that up. However, I'd just go ahead and do that anyways (i.e., use events) then file an issue in go-libp2p about adding address change detection to the swarm.

**Comment by Stebalien** [comment]
> We could poll net.InterfaceAddrs() to see if local addresses have changed from DHCP.

We actually do this (effectively) in "BasicHost" (defined in go-libp2p).

**Comment by raulk** [comment]
The hooking up of the “local addrs updated” event in the host is here: https://github.com/libp2p/go-libp2p/pull/747

**Comment by aarshkshah1992** [comment]
@willscott This PR can be closed as I think you plan to address this change [here](https://github.com/libp2p/go-libp2p-autonat/blob/3410cb68680e1fc98966e086e38e15206a08829a/autonat.go#L148).

**Pull request closed without merging**
